### ISSUE TITLE
Turning USB port(s) power off while keeping data transfer possible?

### ISSUE THREAD

**Issue by reabha** [mvp/uhubctl#329]
Hello,

I'm doing power consumption experiments on Android phones. Some power profilers require the device to be connected to a PC through USB (a RPI4B in my case) while the device is **NOT** charging.

When I use uhubctl I can turn of the USB ports of my RPI4B which then stops charging the device. However, this also results in not being able to communicate with the device through USB. 

Is it possible to turn off the charging/power functionalities of the USB port(s) while keeping its data transfer abilities (so being able to send commands)?

Thanks!

**Comment by mvp** [comment]
Per USB2 protocol spec, host must provide at least 500mA current (for USB3, it is 900mA minimum) in order to establish data connection. So, it is not possible to keep data connection without having device consume current.

However, there are couple ways to still get what you want:
1. Configure client device to not consume current for battery charging. Most devices have ability to do this, however it could be tricky to figure out exactly how to do it. Usually it is some vendor specific sysfs kernel setting, which typically requires root access to change, so you maybe out of luck of your devices are not rooted.
2. Have host to periodically check on your device(s) by shortly turning powering USB using uhubctl, getting current status (e.g. `adb shell something`) and then disconnecting to ensure that device does not continue to charge.
