### ISSUE TITLE
List of unsupported devices?

### ISSUE THREAD

**Issue by jeanpaulgalea** [mvp/uhubctl#347]
Hi,

Thanks for writing and maintaining uhubctl.

Do you have / would you consider maintaining a list of *un*supported devices? It could be useful to determine whether a hub has been tested and known to work, or if it hasn't been tested yet.

FWIW, I tested a [ExSys EX-1178 7 port USB2.0](https://www.exsys.it/prodotto/ex-1178/). It is recognized by uhubctl but does not support VBUS off.

**Comment by mvp** [comment]
I'm sorry, but I cannot boil the ocean. I cannot maintain list of all USB hubs ever produced, it would be many times larger than whole uhubctl repository.

Instead, I would rather maintain list of hubs that are definitely known to work.

Good news is that I expect that all new hubs conforming to USB4 standard should support power switching properly (and work with uhubctl), because they must support power delivery over USB-C, and as far as I know that requires to support proper power switching per port.
