### ISSUE TITLE
Raspberry Pi3B port control

### ISSUE THREAD

**Issue by slartibartfast3** [mvp/uhubctl#357]
This is not really an issue but I am not sure where to put it so apologies if this is the wrong place. Everything I read about the Pi3B says the USB ports are ganged and controlled by port 2. On mine turning off port 2 only turns off USB port 2. The ports seem to be controlled individually. Did this change at some point?
Also can multiple USB ports be turned off with one command?

**Comment by mvp** [comment]
It may appear from uhubctl output that only port 2 is off, but actually voltage should be turned off for all ports if you try to measure it with voltmeter, and all devices connected to other ports should stop working.

uhubctl is simply setting new power state or querying current status for each port from hub chip using USB control transfer messages, and it may report port state as `power` despite not really powering those ports.

RPi 3B+ is somewhat strange in that regard, because it also has more than one internal hub (`1-1` and `1-1.1`), so you have to be specific about which one of those hubs you are talking about, from readme:

##### Raspberry Pi 3B+

  * Main hub `1-1`, all 4 ports ganged, all controlled by port `2` (turns off secondary hub ports as well).
    Port `1` connects hub `1-1.1` below, ports `2` and `3` are wired outside, port `4` not wired.

        uhubctl -l 1-1 -p 2 -a 0

  * Secondary hub `1-1.1` (daisy-chained to main): 3 ports,
    port `1` is used for Ethernet+WiFi, and ports `2` and `3` are wired outside.

You can turn power off (or on) for multiple ports at once either by using subset of ports like `-p 2-4`, or by using `-p all`, or not specifying `-p` option altogether - this is equivalent to `-p all`.
