### ISSUE TITLE
Recommendation for a uhubctl-compatible hub that can handle 5+ 350-400 Mbps devices at the same time?

### ISSUE THREAD

**Issue by FlorentLM** [mvp/uhubctl#444]
Hi there,

Sorry to ask this here as it is definitely not an issue per-se, but after trying many different hubs/PCIe cards I can't seem to find anything that fits my requirements so I figured I'd try asking here...

I would like to receive data from 5 devices at the same time, at a bandwidth of around 350-400 MBps per device, and be able to turn off the USB programatically (because the devices do not have any ON/OFF switch and they get pretty hot when plugged in, even without any transfer happening).

I am looking at external hubs, as the PC that I have at hand is a prebuilt with really bad mobo/PSU (thanks, HP) and PCIe cards seem to be a no go.

Would such thing exist? I tried with two of [these](https://www.amazon.co.uk/gp/product/B09XQKR8RS/) but even with only two of my devices connected the bandwidth wasn't enough - I'm not actually sure why that was the case since they were 10 Gbps and should theuretically allow for 1250 MBps I guess? Would I need 20 Gbps (i.e. USB SS20) hubs?

Thank you very much in advance,

And sorry again for such question

**Comment by mvp** [comment]
If I were you I would prefer multiple PCIe cards mostly due to xhci limit issue as explained in this excellent article https://acroname.com/blog/how-many-usb-devices-can-i-connect.
Each PCIe card should get its own independent USB bus with its own bandwidth limit, and xhci limit.

For me personally Rosonway RSH-A16 works ok, but I am not using high bandwidth devices.
