### ISSUE TITLE
2109:0817 VIA Labs, Inc. USB3.0 Hub

### ISSUE THREAD

**Issue by HanalogInstruments** [mvp/uhubctl#472]
Hi,

This hub working for my weak head HDD to recovery data 
![image](https://user-images.githubusercontent.com/100456607/205549586-1857c49f-f608-4bf2-a677-a42b8933ad79.png)

**Comment by HanalogInstruments** [comment]
> Can you check if it supports vbus off? That is, is connected phone stops charging or connected USB drive completely turns off?

is still charging when power off:
sudo uhubctl -l 1-1 -p 1 -a off

**Comment by mvp** [comment]
In this case we unfortunately do not consider this as supported device :-(

**Comment by HanalogInstruments** [comment]
> In this case we unfortunately do not consider this as supported device :-(

do you recommend another cheap hub like this support vbus off?

**Comment by mvp** [comment]
All hubs listed in current table should work for vbus control - I don't add them otherwise. That said, it is possible that some hubs in the table don't really support vbus because people who reported them didn't test thoroughly enough. Also, sometimes hub vendors change internals without changing the model.

**Comment by mvp** [comment]
As explained in readme, necessary API call to make it possible is not supported by USB kernel driver winusb.sys. So it all depends on Microsoft exposing it somehow, and hopes of this are very low in foreseeable future.
