### ISSUE TITLE
UGreen (VIA) USB C to 3.0 4 port bus powered hub - "working", VBUS not turned off

### ISSUE THREAD

**Issue by voltagex** [mvp/uhubctl#523]
```
New status for hub 2-5 [2109:0817 VIA Labs, Inc. USB3.0 Hub 000000000, USB 3.20, 4 ports, ppps]
  Port 1: 00a0 off
  Port 2: 00a0 off
  Port 3: 00a0 off
  Port 4: 00a0 off
```

I have a little USB light that stays on no matter what command I send. It does not speak any kind of USB protocol though.

If I plug in a flash drive, through a meter that passes data lines, I can see 0.06A being drawn when the port is on and zero when the port is off.

**Comment by mvp** [comment]
Thanks for your report!

Unfortunately, since it doesn't seem to support vbus off, I can't accept it to supported list. Dumb device still being able to get power proves that vbus off is not working. Flash drive not pulling power is most likely because it wasn't able to establish data communication in first few milliseconds and it turned itself off.

If you find any other device that does support vbus off, please report!
