### ISSUE TITLE
Hubs No Longer Available

### ISSUE THREAD

**Issue by tstana** [mvp/uhubctl#528]
May be of general interest to update the list in the main README, a couple of devices no longer supported by manufacturers (EOL):

- [USH304](https://www.digikey.lu/en/products/detail/advantech-corporation/BB-USH304/7428806?s=N4IgTCBcDaIK4GcAWBmADAFhAXQL5A)
- [Delock 62537](https://www.delock.com/produkt/62537/merkmale.html?f=s)

**Comment by mvp** [comment]
Perhaps half of the hub listed in compatibility table are not readily available, but often can be purchased on second hand market like eBay.

Do you have specific documentation or announcements from manufacturers about these products being discontinued?
E g. Delock hub was released very recently, in 2020. I highly doubt that is has been discontinued already. Unless proven otherwise, I'd keep it the way it is.

**Comment by mvp** [comment]
Hmm, sorry, I jumped the gun too soon. Your links indeed prove that these products are EOL. I will update the table to mark 2023 as EOL for them. Thank you for reporting! @tstana
