### ISSUE TITLE
Conrad UPH3440 has one switchable port

### ISSUE THREAD

**Issue by leifhelm** [mvp/uhubctl#536]
The Conrad UPH3440 hub has a VL812 hub chip `2109:0812` USB 3.0, `2109:2812` USB 2.0.
`lsusb -v` says:
```
    Ganged power switching
    Ganged overcurrent protection
```
Note this is the same VID:PID as AK-68ANHUB-BV7A-0004.
For some reason uhubctl does not detected it as a compatible device.

**Comment by mvp** [comment]
It wasn't detected because by default uhubctl only lists hubs that advertise per port power switching - ganged hubs are not. You can try controlling power with `-f` option at your risk, but we don't consider such hubs as officially supported - at least not good enough to be added into supported table.
