### ISSUE TITLE
Aukey CB-C60 work temporary

### ISSUE THREAD

**Issue by myudshlihe** [mvp/uhubctl#593]
I didn't find Aukey CB-C59, but find model CB-C60 and tested it. It seems like working ok, VBUS turn off and back on.
It has 4 USB ports, but ports 1 and 3 control each other power. 
BUT! After few hours turned off ports turns back on. Tested it on all ports. All behave the same.
I suspect CB-C59 can act similiary...

**Comment by mvp** [comment]
Chances are that this is not an issue with Aukey hub, but with your Linux kernel.
It could be this issue: https://github.com/mvp/uhubctl?tab=readme-ov-file#power-comes-back-on-after-few-seconds-on-linux
Basically, something on your system does not like USB ports turned off and wants to enable them back on.
I recommend trying it on Linux with kernel 6.0+ - since this fix https://github.com/mvp/uhubctl/pull/450, Linux will not automatically try to enable power on USB ports.

**Comment by myudshlihe** [comment]
Forgot to mention - I use Mac OS Ventura 13.6.9

**Comment by mvp** [comment]
Closing by inactivity. 
Seems like this hub has enough issues to not be added to supported table.
Feel free to reopen if you have anything to add.
